bug_tracker_django/bug_tracker_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #THIRD PARTY
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    #API
    path('api/v1/', include('api_v1.urls')),
    #LOCAL APPS
    path('', include('core.urls')),
    path('tasks/', include('tasks_app.urls')),
]

bug_tracker_django/core/urls.py
from django.urls import path
from . import views


app_name = "core"
urlpatterns = [
    path("", views.index_view, name="index"),
    path("auth/login/", views.LoginView.as_view(), name="login"),
    path("auth/register/", views.RegisterView.as_view(), name="register"),
    path("auth/logout/", views.logout_view, name="logout"),
    path("docs/", views.DocsView.as_view(), name="docs"),
    path("github/main/", views.MainRepositoryView.as_view(), name="github"),
    path("contact/", views.ContactInfoView.as_view(), name="contact-info"),
    path("contact/job/", views.ContactJobView.as_view(), name="contact-job"),
    path("about/", views.AboutView.as_view(), name="about"),
]

bug_tracker_django/templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Doggo Manager{% endblock %}</title>
    <script src="https://unpkg.com/htmx.org@1.9.9"></script>
    {% tailwind_css %}
    <link rel="stylesheet" href='{% static "css/scrollbar.css" %}' />
    {% block scripts %} {% endblock %}
    {% block styles %} {% endblock %}
</head>
<body class="bg-zinc-50">
    {% url 'core:index' as index_url %}
    {% block header %}
        <div id="#top"></div>
        <header class="flex flex-row justify-between px-2 py-1 bg-yellow-500 text-black fixed w-full top-0 z-50 border-b-2 border-b-black">
            <a href="#top" class="flex justify-start flex-row gap-2">
                <span class="font-bold text-xl align-middle mt-auto mb-auto hover:cursor-pointer">
                    DoggoManager
                </span>
                <img src="{% static 'images/doggo-manager-logo.png' %}" alt="Doggo manager logo" width="48" height="32"/>
            </a>
            {% if request.path != index_url %}
                <nav class="flex flex-row gap-4">
                    <ul class="
                    flex flex-row justify-end gap-4
                    [&>li]:text-base
                    hover:[&>li]:text-red-500
                    hover:[&>li]:font-bold
                    hover:[&>li]:text-xl
                    hover:[&>li]:underline
                    hover:[&>li]:cursor-pointer">
                        <li>Tasks</li>
                        <li>Reports</li>
                        <li>Organizations</li>
                    </ul>
                    {% include "components/cp-circle-avatar.html" with initials="MT" %}
                </nav>
            {% else %}
                <nav class="flex flex-row gap-4">
                    {% if request.user.is_authenticated %}
                        <div class="flex justify-center items-center gap-2">
                            <div>Welcome back!</div>
                            <p class="underline font-bold">
                                <a href="">{{ request.user.username }}</a>
                            </p>
                        </div>
                        {% include "components/cp-circle-avatar.html" with initials="MT" %}
                    {% else %}
                        <div class="flex justify-center items-center gap-2">
                            <a href="{% url 'core:login' %}" class="underline hover:cursor-pointer">Login</a>
                            <a href="{% url 'core:register' %}" class="bg-yellow-700 px-3 py-1 text-white hover:cursor-pointer">Register</a>
                        </div>
                    {% endif %}
                </nav>
            {% endif %}
        </header>
    {% endblock %}
    {% block body %}
    {% endblock %}
</body>
</html>