bug_tracker_django/bug_tracker_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #THIRD PARTY
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    #API
    path('api/v1/', include('api_v1.urls')),
    #LOCAL APPS
    path('', include('core.urls')),
    path('tasks/', include('tasks_app.urls')),
]

bug_tracker_django/core/urls.py
from django.urls import path
from . import views


app_name = "core"
urlpatterns = [
    path("", views.index_view, name="index"),
    path("auth/login/", views.LoginView.as_view(), name="login"),
    path("auth/register/", views.RegisterView.as_view(), name="register"),
    path("auth/logout/", views.logout_view, name="logout"),
    path("docs/", views.DocsView.as_view(), name="docs"),
    path("github/main/", views.MainRepositoryView.as_view(), name="github"),
    path("contact/", views.ContactInfoView.as_view(), name="contact-info"),
    path("contact/job/", views.ContactJobView.as_view(), name="contact-job"),
    path("about/", views.AboutView.as_view(), name="about"),
]

bug_tracker_django/tasks_app/urls.py
from django.urls import path
from . import views

app_name = 'tasks_app'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('list-tasks', views.list_tasks_view, name="list-tasks"),
    path('create-task/', views.CreateTaskView.as_view(), name="create-task"),
    path('create-tag/', views.CreateTagView.as_view(), name="create-tag"),
    path('create-tag-form/', views.empty_new_tag_form_template, name="create-tag-form"),
    path('add-or-create-tag/', views.add_or_create_tag, name="add-or-create-tag"),
]

bug_tracker_django/tasks_app/models.py
from django.db import models
from core.models import CustomUser as User


class CreateUpdateBaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Organization(CreateUpdateBaseModel):
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200, blank=False, null=False)


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f"({self.id})-{self.name}"


class TaskPriorityChoices(models.Choices):
    LOW       = "L"
    NORMAL    = "N"
    HIGHT     = "H"
    INMEDIATE = "I"


class TaskStatusChoices(models.Choices):
    NOT_STARTED = "n"
    ASSIGNED    = "a"
    IN_PROGRESS = "p"
    STOPPED     = "s"
    CANCELED    = "c"
    FINISHED    = "f"


class Task(CreateUpdateBaseModel):
    title = models.CharField(max_length=50)
    tags = models.ManyToManyField(Tag, blank=True)
    description = models.TextField()
    priority = models.CharField(max_length=1, choices=TaskPriorityChoices, default=TaskPriorityChoices.NORMAL, blank=False, null=False)
    due_date = models.DateTimeField(blank=True, null=True)
    organization = models.ForeignKey(Organization, on_delete=models.SET_NULL, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False, related_name="author")
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="assigned_to")
    status = models.CharField(max_length=1, choices=TaskStatusChoices, default=TaskStatusChoices.NOT_STARTED, blank=False, null=False)


class Comment(CreateUpdateBaseModel):
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    content = models.TextField()
    parent_task = models.ForeignKey(Task, on_delete=models.CASCADE, blank=False, null=False)
    parent_comment = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)

bug_tracker_django/tasks_app/forms.py
from django import forms

from .models import Task, Tag


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"

bug_tracker_django/tasks_app/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.template import loader
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from .models import Task, Tag
from .forms import TaskForm, TagForm


@login_required
def index_view(request: HttpRequest):
    return render(request, 'tasks_app/index.html', context={})


@login_required
def list_tasks_view(request: HttpRequest):
    paginator = Paginator(Task.objects.all().order_by("title"), 5)
    page_obj = None
    page_num = request.GET.get("page")
    try:
        page_obj = paginator.page(page_num)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'tasks_app/partials/_tasks-list.html', context={"page_obj": page_obj})


@login_required
def empty_new_tag_form_template(request: HttpRequest):
    return render(request, "tasks_app/partials/_tag-add.html", {})


@login_required
def add_or_create_tag(request: HttpRequest):
    empty_new_tag_form_template = loader.render_to_string("tasks_app/partials/_tag-add.html", {}, request)

    tag_name = request.POST.get("new-tag", None)
    if tag_name == None:
        return HttpResponse(empty_new_tag_form_template, "text/html", 200)

    tag = None
    new_tag_template = ""
    try:
        tag = Tag.objects.get(name=tag_name)
    except Tag.DoesNotExist:
        tag = Tag.objects.create(name=tag_name)
        new_tag_template = loader.render_to_string("tasks_app/partials/_tag.html", {"tag": tag}, request)
        new_tag_template = '<div hx-swap-oob="beforeend:#selected-tags-list">' + new_tag_template + '</div>'
        new_tag_option_hidden = f'<div hx-swap-oob="beforeend:#id_tags"><option value="{tag.id}" selected>{tag.name}</option></div>'

    content = empty_new_tag_form_template + new_tag_template + new_tag_option_hidden
    return HttpResponse(content, "text/html", 200)




class CreateTaskView(LoginRequiredMixin, View):
    def get(self, request: HttpRequest):
        task_create_form = TaskForm()

        return render(request, 'tasks_app/partials/_task-create.html', context={"form": task_create_form})

    def post(self, request: HttpRequest):
        task_create_form = TaskForm(request.POST)
        if task_create_form.is_valid():
            new_task = task_create_form.save()
            clean_task_create_form = TaskForm()
            tasks = Task.objects.all()
            new_task_html = loader.render_to_string("tasks_app/partials/_task-preview-new.html", {"task": new_task}, request)
            task_form_html = loader.render_to_string("tasks_app/partials/_task-create.html", {"form": clean_task_create_form}, request)
            content = new_task_html + task_form_html
            return HttpResponse(content, "text/html", 200)
        return render(request, 'tasks_app/partials/_task-create.html', context={"form": task_create_form})


class CreateTagView(LoginRequiredMixin, View):
    def get(self, request: HttpRequest):
        tag_create_form = TagForm()
        return render(request, 'tasks_app/partials/_tag-create.html', context={"form": tag_create_form})

    def post(self, request: HttpRequest):
        pass

bug_tracker_django/tasks_app/templates/tasks_app/partials/_tag-add.html
<form hx-post="{% url 'tasks_app:add-or-create-tag' %}" >
    {% csrf_token %}
    <label for="new-tag" class="flex flex-row">
        <input type="text" name="new-tag" id="new-tag" value="" placeholder="#tag-name"/>
        <button>Add tag</button>
    </label>
</form>

bug_tracker_django/tasks_app/templates/tasks_app/partials/_tag-create.html
<div>
    <form hx-post="{% url 'tasks_app:create-tag' %}" hx-target="#tag-form-notification">
        {% csrf_token %}
        {{form.as_div}}
        <button type="submit">Add new Tag </button>
    </form>
    <div id="tag-form-notification"></div>
</div>

bug_tracker_django/tasks_app/templates/tasks_app/partials/_tag.html
<span class="bg-red-800 px-4 py-2 rounded-md text-white">
   #{{ tag.name }}
</span>

bug_tracker_django/tasks_app/templates/tasks_app/partials/_task-create.html
<form
    hx-post="{% url 'tasks_app:create-task' %}" hx-swap="outerHTML"
    class="
        flex flex-col
        rounded-lg
        px-5 py-5
        bg-gradient-to-br from-violet-700 to-violet-400 text-white
        w-full md:w-[50%] md:min-w-[600px] md:max-w-[900px] m-auto">
    {% csrf_token %}
    {% for field in form %}
        <div class="flex flex-col [&>input]:rounded-md [&>textarea]:rounded-md text-violet-700">
            {% if field.name == "tags" %}
                <div hx-get="{% url 'tasks_app:create-tag-form' %}" hx-trigger="click" hx-swap="outerHTML">Hellooo</div>
                <div id="selected-tags-list"></div>
                <select id="id_tags" name="tags" multiple class="hidden"></select>
            {% else %}
                <label for="{{ field.id_for_label }}" class="text-white font-medium text-xl">{{ field.label}}</label>
                {{ field }}
            {% endif %}
            {{ field.errors }}
        </div>
    {% endfor %}
    {{ form.non_field_errors }}
    {% comment %} {{ form.as_div}} {% endcomment %}
    <button type="submit"> New Task </button>
</form>

bug_tracker_django/tasks_app/templates/tasks_app/partials/_task-preview-new.html
<div hx-swap-oob="beforeend:#tasks-list">
    <article>
        <h2>{{ task.title }}<h2>
        <div class="tags">
        {% comment %} {% for tag in task.tags %}
            {% include "tasks_app/partials/_tag.html" %}
        {% endfor%} {% endcomment %}
        </div>
    </article>
</div>

bug_tracker_django/tasks_app/templates/tasks_app/partials/_task-preview.html
{% load static %}
<article  id="new-task" class="px-10 py-5 mx-2 my-10 h-48">
    <header class="flex flex-row justify-between align-middle">
        <h2 class="text-3xl inline-flex flex-row justify-start align-baseline bg-violet-700 rounded-tr-lg rounded-tl-lg pt-3 pl-3"><span class="mr-5">{{ task.title }}</span> <span
            class="text-sm font-mono
                px-5 py-3
                rounded-md
                {% if task.priority == "H" or task.priority == "I" %}
                    bg-red-900 text-white font-bold
                {% else %}
                    bg-yellow-600 text-black
                {% endif %}
                ">{{task.get_priority_display}}</span>
        <h2>
        <div class="flex flex-row align-baseline">
            <p>{{ task.assigned_to }} </p>
            <svg class="w-5 h-5">
                <use href="{% static 'svg/icons/user.svg' %}#my_profile"></use>
            </svg>
        </div>
    </header>
    <div class="tags">
    {% comment %} {% for tag in task.tags %}
        {% include "tasks_app/partials/_tag.html" %}
    {% endfor%} {% endcomment %}
    </div>
    <p class="overflow-x-hidden overflow-y-scroll h-32 px-2 py-2 border-2 border-solid border-violet-700"> Lorem ipsum dolor sit, amet consectetur adipisicing elit. In esse adipisci ipsa deserunt repudiandae quod facere odit, asperiores dolore soluta fugiat consectetur accusamus repellat eaque dolorem velit similique vel laudantium.
    Hic accusamus eligendi libero cupiditate quis ducimus, aperiam sunt numquam reiciendis fugiat quod amet quaerat ea alias neque earum perspiciatis dolore corrupti similique consequatur eum culpa voluptatem in. Nihil, veritatis.
    Explicabo ab, perferendis accusantium commodi tempora, sunt tempore maiores voluptatem quasi culpa repellat vitae? Natus, est culpa itaque, officia corporis quis molestiae cumque illo modi iure possimus odio veniam optio.
    Exercitationem, magnam fugit illum veniam facilis enim in quos sed, molestiae maiores totam vitae. Et sint ea quaerat alias distinctio officiis qui excepturi. Eos debitis ab eius voluptatem expedita nisi.
    Praesentium, laudantium soluta dolor molestias possimus sed impedit commodi dignissimos optio vitae nisi eveniet consequatur, provident deleniti velit non illum nostrum quia ab eum ut! Ullam dolorum veritatis ipsum illo.
    Alias quaerat praesentium earum dolorem corporis saepe, doloribus ea iure nihil adipisci nostrum eaque laborum quod amet in? Recusandae sit accusantium quidem neque saepe eum delectus perferendis, incidunt adipisci laborum?
    Perferendis voluptatibus error ea esse laudantium deleniti sit fugit eos omnis voluptatum! Sequi reprehenderit at alias quidem, veniam eaque quo, asperiores nihil tenetur quibusdam itaque cum sint expedita consequatur repellat!
    Placeat recusandae necessitatibus itaque delectus rerum fugit est aliquam dolor ex, repudiandae beatae, accusamus magnam totam voluptates id doloremque iusto in dignissimos unde perspiciatis! Magni nemo inventore repudiandae quas porro.
    Sequi, provident vitae? Quis assumenda optio fugiat hic. Eum voluptatum soluta nemo quam corrupti sit ut ab, illum repellendus animi ad laborum dolorem, aut consequuntur cupiditate debitis! Iusto, nihil quisquam!
    Rerum perspiciatis unde quidem laboriosam! Quidem, vel quod numquam adipisci iusto delectus quasi culpa sunt maxime veniam esse voluptas facilis quibusdam nihil, sapiente beatae illum eum natus illo? Quam, tempore.
    </p>
    {% if task.comments %}
        <h3>Comments</h3>
    {% else %}
        <h3>No comments, <button>Add a new one?</button></h3>
    {% endif %}
</article>

bug_tracker_django/tasks_app/templates/tasks_app/partials/_tasks-list.html
<div id="tasks-list">
    <div class="flex justify-between align-baseline mx-5 my-5 px-5 py-5">
        {% if page_obj.has_previous %}
            <button
                hx-get="{% url 'tasks_app:list-tasks' %}?page={{ page_obj.previous_page_number }}"
                hx-target="#tasks-list"
                hx-swap="innerHTML"
                class="text-white bg-violet-600 px-5 py-5 text-3xl"
            > &lt; </button>
        {% else %}
            <button class="px-5 py-5 text-3xl invisible"> &lt; </button>
        {% endif%}
        <div>
            {% for page in page_obj.paginator.page_range %}
                <button
                    hx-get="{% url 'tasks_app:list-tasks' %}?page={{ page }}"
                    hx-target="#tasks-list"
                    hx-swap="innerHTML"
                    class="
                        px-1 py-1 text-xl mx-1 my-1
                        w-10 h-10
                        text-white
                        {% if page_obj.number == page %}
                            bg-violet-950
                        {% else %}
                            bg-violet-600
                        {% endif %}
                    "
                > {{ page }} </button>
            {% endfor %}
        </div>

        {% if page_obj.has_next %}
            <button
                hx-get="{% url 'tasks_app:list-tasks' %}?page={{ page_obj.next_page_number }}"
                hx-target="#tasks-list"
                hx-swap="innerHTML"
                class="text-white bg-violet-600 px-5 py-5 text-3xl"
            > &gt; </button>
        {% endif %}
    </div>
    {% for task in page_obj %}
        {% include "tasks_app/partials/_task-preview.html" %}
    {% endfor %}
    <div id="new-task"></div>
</div>